### ISSUE TITLE
Errors on function addWatermark(FileUploadEvent $event)

### ISSUE THREAD

**Issue by MinhVu2711** [ckfinder/ckfinder-plugin-imagewatermark-php#2]
![image](https://user-images.githubusercontent.com/68370102/147722695-e52f327b-2bfe-40a7-bf13-db7f4ffe40d8.png)
 I don't know how to make 'resource' to 'GdImage', please help me find the place to config

Besides that, `the code on line 109` is not working. So that `$watermarkImage` is empty and makes the whole code after can not run and cause some errors.

I try to `var_dump(file_get_contents($watermarkImagePath));` but it doesn't show anything.
![image](https://user-images.githubusercontent.com/68370102/147723337-a1d6c3ea-dc5f-4d0b-bc12-2ff76b5e820a.png)

Tks for reading this, hope I will get a reply soon

**Comment by zaak** [comment]
Hi @vuquocminh99. I have just checked the plugin and everything seems to work as expected.
1. As for `GdImage` and `resource`, it's a matter of configuration of PHP version in your IDE.
2. If `$watermarkImagePath` is not set it means you have not configured the plugin, please have a look at the readme.

For now, I'm closing this ticket.

**Comment by MinhVu2711** [comment]
I have fixed, tks a lot. The problem is the watermark_image size is bigger than the uploaded_image

I have another problem now.
I would like to watermark only product images (on Product admin page), and I think that I could config the watermark plugin wherever I want, is it true?
Example: Here is the code on Product admin page
```
CKFinder.popup({
  chooseFiles: true,
  width: 800,
  height: 600,
  plugins: [
      `/ckfinder/plugins/ImageWatermark/ImageWatermark.php` // is it right? I use this but the uploaded_image wasn't watermarked
  ],
  .....
})
```
What I have to do to solve it, please help me.
I really appreciate your help
